### ISSUE TITLE
clearer "how to tweak"

### ISSUE THREAD

**Issue by stopachka** [wit-ai/witty-weather#14]
![image](https://cloud.githubusercontent.com/assets/984574/17609002/a709e9ce-5fe5-11e6-9f98-cd47055d65ef.png)

**Comment by dwwoelfel** [comment]
Might be a good idea to rename it from "how to tweak" to something like "Build your own bot" with a byline "Use witty weather as a template to build your own bot. It has 3 main parts you can adapt:"

IIUC, the goal is to give developers a template that they can use to build their own apps. It will be easier to understand the purpose if you call it out explicitly.

**Comment by stopachka** [comment]
love it! mind giving README.md a quick edit? Love the wording you used above

**Comment by stopachka** [comment]
Awesome @dwwoelfel !
